### ISSUE TITLE
Setup Kanban Board for the project

### ISSUE THREAD

**Issue by alonsofl** [alonsofl/recipe-app#12]
## Summary
We've added the [Kanban Board](https://github.com/alonsofl/recipe-app/projects/1) for the project:
Link: https://github.com/alonsofl/recipe-app/projects/1

Team Member 1: [Abimbola Buari](https://github.com/bimbolabuari)
Team Member 2: [Alonso Falconi](https://github.com/alonsofl)

### Note to the reviewer :wave:
My coding partner is having electrical issues and that is the reason why she has not been able to accept the invitation to the repo. But after accepting the only thing it's to assign her to the issues. Everything else has been done according to the requirements.
I would really appreciate your comprehension :raised_hands:

![image](https://user-images.githubusercontent.com/81522435/141824046-b7b50c96-b600-409c-8d3f-2d303c47f8fd.png)

**Comment by Lameck1** [comment]
Hi, @alonsofl,

The reasoning you've given is understandable to me. I wish you and your partner all the best.
Your Kanban board is properly set up, here are some highlights:
- You've distributed the tasks equally ✔️ 
- The tasks described cover every requirement ✔️ 

Setting up the board is now complete, please go ahead and start on the project.
 
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by alonsofl** [comment]
Thanks, @Lameck1! :raised_hands:
